name: SSH deploy on push
on: push
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync deploy
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: .
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.REMOTE_KEY }}
          remote_path: ${{ secrets.REMOTE_PATH }}
      - run: npm install
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    # This will deploy your code to your server if it is merged into master.
    # You can change the branch to a common name like develop or staging.
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Executing deploy command
      uses: burnett01/rsync-deployments@5.2.1
      with:
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: ${{ secrets.REMOTE_KEY }}
        remote_path: ${{ secrets.REMOTE_PATH }}
        script: cd /home/zlotnika/zlotnik.website/www/ && ./deploy.sh
